language: rust
rust:
  - stable
  - nightly
script:
  - CC=musl-gcc cargo build --release --verbose --target=x86_64-unknown-linux-musl
  - CC=musl-gcc cargo test --release --verbose --target=x86_64-unknown-linux-musl
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: false